version '0.0.2'

services:

    backend:
        container_name: backend
        build: ./backend
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            - MONGO_URL: mongodb://mongo:27017/shopping-cart
        volumes:
            - ./backend:/usr/src/app
        command: node app.js

    mongo:
        image: mongo:5.0
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
    
volumes:
    mongodata:
    