version '0.0.1'

services:

    backend:
        container_name: backend
        build: ./backend
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            MONGO_URL: mongodb://mongo:27017/ecommerce

    frontend:
        build: ./frontend
        ports:
            - "8080:8080"
        depends_on:
            - backend
    
    mongo:
        image: mongo:5.0
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
    
volumes:
    mongodata:
    