apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  containers:
  - name: backend
    image: backend-image:latest
    ports:
    - containerPort: 3000
  type: LoadBalancer
